"""GitHub Pages static site generator."""
import json
import shutil
from datetime import datetime
from pathlib import Path

from .config import get_data_dir
from .models import Member, Branch, MemberStatus, Appearance
from .storage import load_members, load_appearances


PAGE_HEADER = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Hololive Collab Tracker</title>
<link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
<style>
.status-active {{ color: #2a9d8f; }}
.status-graduated {{ color: #e76f51; }}
.status-terminated {{ color: #d62828; }}
.badge {{ font-size: 0.8em; padding: 2px 6px; border-radius: 4px; }}
.badge-active {{ background: #e0f4f0; color: #2a9d8f; }}
.badge-graduated {{ background: #fde8e0; color: #e76f51; }}
.badge-terminated {{ background: #fce0e0; color: #d62828; }}
.app-row {{ display: flex; gap: 1em; align-items: center; padding: 0.5em; border-bottom: 1px solid #eee; }}
.app-row:hover {{ background: #f5f5f5; }}
.app-date {{ min-width: 100px; color: #666; }}
.app-channel {{ min-width: 150px; }}
.app-title {{ flex: 1; }}
.app-status {{ min-width: 30px; text-align: center; }}
.branch-group {{ margin-bottom: 2em; }}
.member-grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 1em; }}
.member-card {{ padding: 1em; border: 1px solid #ddd; border-radius: 8px; }}
.member-card:hover {{ box-shadow: 0 2px 8px rgba(0,0,0,0.1); }}
.filter-bar {{ margin: 1em 0; padding: 1em; background: #f8f9fa; border-radius: 8px; }}
</style>
</head>
<body>
<header>
<nav>
<a href="../">Home</a>
<a href="../stats.html">Stats</a>
<a href="../unknowns.html">Unknowns</a>
</nav>
<h1>Hololive Collab Tracker</h1>
</header>
<main>
"""

PAGE_FOOTER = """
</main>
<footer>
<p>Generated by HCAT at {now}</p>
</footer>
</body>
</html>"""


def _status_badge(status: str) -> str:
    cls = {
        "active": "badge-active",
        "graduated": "badge-graduated",
        "terminated": "badge-terminated",
    }.get(status, "badge-active")
    return f'<span class="badge {cls}">{status}</span>'


def _status_icon(status: str) -> str:
    return {"unreviewed": "◇", "confirmed": "✅", "rejected": "❌"}.get(status, "◇")


def build_site():
    data_dir = get_data_dir()
    site_dir = data_dir.parent / "docs"
    if site_dir.exists():
        shutil.rmtree(site_dir)
    site_dir.mkdir(parents=True)

    members = load_members()
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    # ── Index page: member list ──
    html = [PAGE_HEADER.format()]
    html.append('<div class="filter-bar">')
    html.append('<label>Filter: <input type="text" id="filter" placeholder="Search member..." oninput="filterMembers()"></label>')
    html.append('</div>')

    for b in [Branch.EN, Branch.JP, Branch.ID, Branch.OFFICIAL, Branch.DEV_IS, Branch.HOLOSTARS, Branch.OTHER]:
        branch_members = [m for m in members if m.branch == b]
        if not branch_members:
            continue
        branch_members.sort(key=lambda m: (m.status != MemberStatus.ACTIVE, m.handle))

        html.append(f'<div class="branch-group" data-branch="{b.value}">')
        html.append(f'<h2>{b.value} ({len(branch_members)})</h2>')
        html.append('<div class="member-grid">')

        for m in branch_members:
            apps = load_appearances(m.handle)
            count = len(apps)
            confirmed = sum(1 for a in apps if a.status == "confirmed")
            photo = f'<img src="{m.photo_url}" alt="" style="width:48px;height:48px;border-radius:50%;object-fit:cover;display:block;margin:0 auto .25em">' if m.photo_url else ''
            html.append(f'<div class="member-card" data-name="{m.name.lower()} {m.handle.lower()}">')
            html.append(photo)
            html.append(f'<h3><a href="members/{m.handle}.html">@{m.handle}</a></h3>')
            html.append(f'<p><strong>{m.name}</strong> {_status_badge(m.status.value)}</p>')
            html.append(f'<p>Appearances: {count} ({confirmed} confirmed)</p>')
            html.append('</div>')

        html.append('</div></div>')

    html.append(PAGE_FOOTER.format(now=now))
    html.append('<script>function filterMembers(){const f=document.getElementById("filter").value.toLowerCase();document.querySelectorAll(".member-card").forEach(c=>{c.style.display=c.dataset.name.includes(f)?"":"none"})}</script>')
    (site_dir / "index.html").write_text("\n".join(html), encoding="utf-8")

    # ── Member pages ──
    members_dir = site_dir / "members"
    members_dir.mkdir()

    for m in members:
        apps = load_appearances(m.handle)
        html = [PAGE_HEADER.format()]
        photo = f'<img src="{m.photo_url}" alt="" style="width:64px;height:64px;border-radius:50%;object-fit:cover;float:left;margin-right:1em">' if m.photo_url else ''
        html.append(f'<div style="display:flex;align-items:center;gap:1em;margin-bottom:1em">')
        html.append(photo)
        html.append(f'<div><h2>@{m.handle} — {m.name} {_status_badge(m.status.value)}</h2>')
        if m.graduated_at:
            html.append(f'<p>Graduated: {m.graduated_at}</p>')
        html.append(f'<p>Branch: {m.branch.value}</p></div></div>')

        if not apps:
            html.append('<p>No appearances recorded yet.</p>')
        else:
            by_channel = {}
            for a in apps:
                by_channel.setdefault(a.channel_handle, []).append(a)

            html.append(f'<p>Total: {len(apps)} appearances</p>')
            html.append('<div class="filter-bar">')
            html.append('<label>Filter: <input type="text" id="filter" placeholder="Search channel..." oninput="filterApps()"></label>')
            html.append(f'<label>Show: <select id="statusFilter" onchange="filterApps()"><option value="all">All</option><option value="confirmed">Confirmed</option><option value="unreviewed">Unreviewed</option></select></label>')
            html.append('</div>')

            html.append('<table><thead><tr><th>Date</th><th>Channel</th><th>Title</th><th>Method</th><th>Status</th></tr></thead><tbody>')
            for a in sorted(apps, key=lambda x: x.published_at, reverse=True):
                date = a.published_at[:8] if len(a.published_at) >= 8 else "????"
                date_fmt = f"{date[:4]}-{date[4:6]}-{date[6:8]}" if len(date) == 8 else date
                html.append(f'<tr class="app-row" data-channel="{a.channel_handle.lower()}" data-status="{a.status}">')
                html.append(f'<td class="app-date">{date_fmt}</td>')
                html.append(f'<td class="app-channel">@{a.channel_handle}</td>')
                html.append(f'<td class="app-title"><a href="{a.url}" target="_blank">{a.title[:80]}</a></td>')
                html.append(f'<td>{a.detection_method}</td>')
                html.append(f'<td class="app-status">{_status_icon(a.status)}</td>')
                html.append('</tr>')
            html.append('</tbody></table>')

        html.append(PAGE_FOOTER.format(now=now))
        html.append('<script>function filterApps(){const f=document.getElementById("filter").value.toLowerCase();const s=document.getElementById("statusFilter").value;document.querySelectorAll(".app-row").forEach(r=>{const matchChannel=r.dataset.channel.includes(f);const matchStatus=s==="all"||r.dataset.status===s;r.style.display=matchChannel&&matchStatus?"":"none"})}</script>')
        (members_dir / f"{m.handle}.html").write_text("\n".join(html), encoding="utf-8")

    # ── Stats page ──
    html = [PAGE_HEADER.format()]
    html.append('<h2>Statistics</h2>')
    total_apps = 0
    html.append('<table><tr><th>Branch</th><th>Members</th><th>Total Appearances</th><th>Confirmed</th></tr>')
    for b in Branch:
        branch_members = [m for m in members if m.branch == b]
        if not branch_members:
            continue
        total = 0
        confirmed = 0
        for m in branch_members:
            apps = load_appearances(m.handle)
            total += len(apps)
            confirmed += sum(1 for a in apps if a.status == "confirmed")
        total_apps += total
        html.append(f'<tr><td>{b.value}</td><td>{len(branch_members)}</td><td>{total}</td><td>{confirmed}</td></tr>')
    html.append(f'<tr><strong><td>Total</td><td>{len(members)}</td><td>{total_apps}</td><td>—</td></strong></tr>')
    html.append('</table>')
    html.append(PAGE_FOOTER.format(now=now))
    (site_dir / "stats.html").write_text("\n".join(html), encoding="utf-8")

    # ── Unknowns page ──
    unknowns = json.loads((data_dir / "unknowns.json").read_text(encoding="utf-8")) if (data_dir / "unknowns.json").exists() else []
    html = [PAGE_HEADER.format()]
    html.append('<h2>Unknown @Handles</h2>')
    html.append(f'<p>{len(unknowns)} unknown handles discovered during scanning.</p>')
    if unknowns:
        html.append('<table><tr><th>Handle</th><th>First Seen In</th><th>Video</th></tr>')
        for u in sorted(unknowns, key=lambda x: x["handle"]):
            html.append(f'<tr><td>@{u["handle"]}</td><td>@{u["first_seen_in"]}</td><td><a href="{u["video_url"]}" target="_blank">{u["video_title"][:60]}</a></td></tr>')
        html.append('</table>')
    html.append(PAGE_FOOTER.format(now=now))
    (site_dir / "unknowns.html").write_text("\n".join(html), encoding="utf-8")

    print(f"Site built: {site_dir}")
